filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # only containers with co.elastic.logs/enabled: true will be discovered
      hints.default_config.enabled: false
output.elasticsearch:
  hosts: ["104.248.152.167:9200"] 
  username: "elastic"
  password: "abc123"